apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      # terminationGracePeriodSeconds: 10
      containers:
        - name: reverse-proxy
          imagePullPolicy: Always
          image: {your_image:hash}
          # Health Checks
          livenessProbe:
            httpGet:
              # path: /
              port: 9090
              # httpHeaders:
              # - name: Custom-Header
              # value: Awesome
            initialDelaySeconds: 5
            periodSeconds: 5              
          env:

            - name: BACKEND_URL
              value: "sis"
            - name: BACKEND_PORT
              value: "3030"
            - name: BACKEND_URL2
              value: "sis-1"
            - name: BACKEND_PORT2
              value: "3030"
            - name: BACKEND_URL3
              value: "sis-2"
            - name: BACKEND_PORT3
              value: "3030"
          command:
            [
              "/bin/bash",
              "-c",
              "envsubst '$$BACKEND_URL $$BACKEND_PORT' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'",
            ]
          ports:
            - containerPort: 9090
